### ISSUE TITLE
Q: Increase tip attribution limit ?

### ISSUE THREAD

**Issue by vexy** [scotteg/SwiftDevTips#6]
Hey there @scotteg
Just stumbled upon this cool repo, and thought about sharing few tips as I find the general repo idea quite useful 👍 

Rules in `CONTRIBUTING.MD` are quite clear about 140 chars limit, however, some quality links out there are blog based, and because of underlying need for SEO, their link sizes might go beyond 140. Is there any chance to simply increase (URL) link limit size to prevent spawning another `.md` just for that purpose ?

**Comment by scotteg** [comment]
Hi @vexy, sure, I’ll revise the contribution guidelines to permit long links. Thanks for bringing this up.
